### ISSUE TITLE
Chart to table

### ISSUE THREAD

**Issue by Aaryaveerkrishna23** [khuangaf/Awesome-Chart-Understanding#1]
Are you working on chart to table conversion ?

**Comment by khuangaf** [comment]
Hi! Our survey does cover chart-to-table conversion. See the [Tool Augmentation](https://github.com/khuangaf/Awesome-Chart-Understanding?tab=readme-ov-file#tool-augmentation) section for more details.

As for our lab, we indeed have worked on this problem in the paper [Do LVLMs Understand Charts? Analyzing and Correcting Factual Errors in Chart Captioning](https://arxiv.org/abs/2312.10160). The checkpoints have also been released on [Huggingface](https://huggingface.co/khhuang/chart-to-table).
